config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session
  resources :users, only: %i[create new show]

  root 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_reader :password

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6 }, allow_nil: true
  validates :session_token, presence: true, uniqueness: true

  before_validation :ensure_session_token

  def self.find_by_credentials(username:, password:)
    user = User.find_by(username:)
    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_unique_session_token
    save!
    session_token
  end

  def generate_unique_session_token
    loop do
      session_token = SecureRandom.urlsafe_base64(16)
      return session_token unless User.exists?(session_token:)
    end
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def login!(user)
    Current.user = user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def current_user
    return nil if session[:session_token].nil?

    Current.user ||= User.find_by(session_token: session[:session_token])
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    render :new, locals: { user: User.new }
  end

  def create
    user = User.find_by_credentials(
      username: params[:user][:username],
      password: params[:user][:password]
    )

    if user.nil?
      render json: 'Invalid credentials'.to_json, status: :unprocessable_entity
    else
      login!(user)
      redirect_to user_url(user.id), notice: 'Log in success!'
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :require_current_user!, except: %i[create new]
  before_action :authorize, except: %i[create new]

  def show
    user = User.find_by(id: params[:id])
    render :show, locals: { user: }
  end

  def new
    render :new, locals: { user: User.new }
  end

  def create
    user = User.new(user_params)
    if user.save
      login!(user)
      redirect_to user_url(user.id), notice: 'Registration success!'
    else
      render json: user.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def authorize
    render json: 'What are you doing here?'.to_json, status: :forbidden if params[:id] != current_user.id.to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <% if !current_user.nil? %>
      <ul>
        <li>Logged in as: <%= current_user.username %></li>
        <li>
          <%= button_to 'Logout', session_path, method: :delete %>
        </li>
      </ul>
    <% end %>

    <% if flash[:notice] %>
      <div>
        <%= flash[:notice] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<div>
  <h1><%= form_header %></h1>
  <%= form_with url: form_path, scope: :user do |f| %>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.submit submit_label %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render partial: 'shared/form', locals: { 
  model: user,
  form_path: users_path,
  form_header: 'Sign up!',
  submit_label: 'Sign up' } 
%>

<div>
  <p>Already have an account?</p>
  <%= link_to 'Sign in', new_session_path %>
</div>

app/views/users/show.html.erb
<h1><%= user.username %></h1>

<p>hell0 dear!</p>